### ISSUE TITLE
ESP-IDF built-in driver doesn't work right

### ISSUE THREAD

**Issue by bbulkow** [bbulkow/FastLED-idf#7]
In release versions 4.1, 4.2, and master, the system driver is enabled by default, because the code doesn't crash.

However, it also doesn't work. The colors are terribly wrong, so it seems the conversion going into ESP-IDF must be bad, or the bit rate is bad, or something.

First test will be to see if the build-in interrupt handler at least is working under the later releases just so something works, then to go after the actual flaw causing the driver to not work.

**Comment by plebed** [comment]
Maybe the problem is caused by https://github.com/espressif/esp-idf/issues/5524

**Comment by bbulkow** [comment]
Thanks for the pointer. This repo is now a fork of https://github.com/samguyer/FastLED , and thus all the code has changed, so needs to be retested. I don't think Sam's code was correct for the built in driver - I sent him a pull request.

I will keep an eye on 5524, thanks.

**Comment by bbulkow** [comment]
Seems to work now.
